//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int postid { get; set; }
        public string uid { get; set; }
        public System.DateTime date { get; set; }
        public string text { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
